# Configuration File

data_path: './data/depression_data.csv'  # 1. Data file name and its path

input_features:  # 2. List of features to use as input
  - Marital Status
  - Education Level
  - Number of Children
  - Smoking Status
  - Physical Activity Level
  - Employment Status
  - Alcohol Consumption
  - Dietary Habits
  - Sleep Patterns
  - History of Substance Abuse
  - Family History of Depression
  - Chronic Medical Conditions
  - Age
  - Income
  - Age Range Life Stage Based
  - Age Range Health Based
  - Income Category UK

target_column: 'History of Mental Illness'  # 3. Output feature column name

algorithms:  # 4. Name of Algorithms to use
  - LogisticRegression
  - RandomForest
  - XGBoost

hyperparameters:  # 5. Hyperparameters to use
  LogisticRegression:
    solver: ['liblinear', 'saga']
    penalty: ['l1', 'l2', 'elasticnet']
    C: [0.001, 0.01, 0.1, 1, 10]
    l1_ratio: [0.1, 0.5, 0.9]  # Only used if penalty is 'elasticnet'
  RandomForest:
    n_estimators: [50, 100, 200]
    max_depth: [None, 10, 20]
    min_samples_split: [2, 5]
    min_samples_leaf: [1, 2]
    max_features: ['sqrt', 'log2']
    bootstrap: [True, False]
  XGBoost:
    max_depth: [3, 5, 10]
    learning_rate: [0.01, 0.1, 0.2]
    n_estimators: [50, 100, 150]
    subsample: [0.5, 0.8, 1.0]
    colsample_bytree: [0.5, 0.7, 1.0]
    gamma: [0, 1]
    reg_alpha: [0, 0.01]
    reg_lambda: [1, 0.1]

random_grid_params:  # 6. RandomGrid parameters
  n_jobs: 4
  n_iter: 25
  cv: 4